### ISSUE TITLE
contains algorithm seems incorrect for a simple test

### ISSUE THREAD

**Issue by GopherJ** [georust/geo#528]
```rust
use std::convert::TryInto;

use geo::{prelude::Contains, Point, Polygon};
use geojson::Feature;
use serde_json::json;
fn main() {
    let j = json!({
      "type": "Feature",
      "properties": {
        "id": 62738,
        "name": "Test",
        "tags": [],
        "rgb_color": null,
        "level": 1,
        "type": "map_zone"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              2.32860065124561,
              48.8793876653422
            ],
            [
              2.32863068195301,
              48.8793872280681
            ],
            [
              2.3286312649851,
              48.8794041359986
            ],
            [
              2.32860006821353,
              48.8794028241764
            ],
            [
              2.32860065124561,
              48.8793876653422
            ]
          ]
        ]
      }
    });

    let feature_serialized = serde_json::to_string(&j).unwrap();
    let feature_deserialized: Feature = serde_json::from_str(&feature_serialized).unwrap();

    let point = Point::new(48.8793974057327, 2.32861822943227);

    let polygon: Polygon<f64> = feature_deserialized
        .geometry
        .unwrap()
        .value
        .try_into()
        .unwrap();

    assert!(polygon.contains(&point));
}
```

**Comment by GopherJ** [comment]
```toml
[dependencies]
geo        = { version = "0.15.0" }
geo-types  = "0.6.1"
geojson    = { version = "0.20.1", features = ["geo-types"] }
serde_json = "1.0.59"

```
