### ISSUE TITLE
Should  we enable dependabot?

### ISSUE THREAD

**Issue by michaelkirk** [georust/geo#863]
[Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) is a github bot that will automatically open PR's with dependency updates.

The PR's look like this: https://github.com/urschrei/polylabel-rs/pull/23

Until now we've been using the very-reliable and polite [dependa-martin](@martinfrances107) (see #849, #857, #858, #859), and really I have no complaints, but it doesn't seem super scaleable. 

What would people think about enabling dependabot for the geo/geo-types repo?

**Comment by martinfrances107** [comment]
ha-ha thank you... I am blushing slightly, very un-robot-like of me.

[Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) sounds like a good idea.

I am reading this config guide

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

and trying to set a series of discussion points ... which will then get encoided in the various config settings.
One item of complexity I see is that our extensive use of work spaces ( which is a good thing)  means that  we will have a 
very detailed dependabot.yaml file.

When I use this rustcrate to auto generate a sample dedendabot.yaml files. I see that a complex skeleton is already constructed  for us.
https://github.com/andreimoustache/rust-dependabot-generator

Can I starting the discussion off by suggesting that we mandate a weekly check for most workspaces but set the more sensitive 
geo-types to be on a 6 month upgrade warning cycle?


`cat  .github/dependabot.yaml `

```

---
version: 2
updates:
  - package-ecosystem: cargo
    directory: geo
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: geo/fuzz
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: geo-bool-ops-benches
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: jts-test-runner
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: geo-postgis
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: geo-test-fixtures
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: geo-types
    schedule:
      interval: weekly


```
